-- MySQL Script generated by MySQL Workbench
-- seg 11 jul 2022 21:41:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema isaa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_nodeRed` ;

-- -----------------------------------------------------
-- Schema isaa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_nodeRed` DEFAULT CHARACTER SET UTF8MB4;
SHOW WARNINGS;
USE `db_nodeRed` ;

-- -----------------------------------------------------
-- Table `Leitura`
-- -----------------------------------------------------

SHOW WARNINGS;
CREATE TABLE `Leitura` (
	  `id` INT NOT NULL AUTO_INCREMENT,
	  `valor` VARCHAR(45) NOT NULL,
	  PRIMARY KEY (`id`)
  )
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
